# Generated by Django 2.2 on 2021-09-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Item', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificate', models.IntegerField()),
                ('precioTotal', models.FloatField(blank=True, default=None, null=True)),
                ('comprador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Usuario.Comprador')),
                ('items', models.ManyToManyField(to='Item.Item')),
            ],
        ),
    ]
