# Generated by Django 2.2 on 2021-09-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='hubEntrega',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='hubRecepción',
            field=models.IntegerField(null=True),
        ),
    ]
