# Generated by Django 2.2 on 2021-09-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0003_auto_20210923_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='hubEntrega',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='hubRecepcion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='identificate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
