# Generated by Django 2.2 on 2021-09-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0006_orden_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='status',
            field=models.CharField(choices=[('Creada', 'Creada'), ('Alistamiento', 'Alistamiento'), ('Lista', 'Lista'), ('En Hub Despacho', 'En Hub Despacho'), ('Volando', 'Volando'), ('En Hub Llegada', 'En Hub Llegada'), ('Lista Recoger', 'Lista Recoger'), ('Entregada', 'Entregada'), ('Cancelada', 'Cancelada')], default='Creada', max_length=255),
        ),
    ]
