# Generated by Django 2.2 on 2021-10-21 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField(blank=True, default=None, null=True)),
                ('alto', models.FloatField(blank=True, default=None, null=True)),
                ('ancho', models.FloatField(blank=True, default=None, null=True)),
                ('largo', models.FloatField(blank=True, default=None, null=True)),
                ('peso', models.FloatField(blank=True, default=None, null=True)),
                ('cantidadDisponible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificate', models.IntegerField()),
                ('precioTotal', models.FloatField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('Creada', 'Creada'), ('Alistamiento', 'Alistamiento'), ('Lista', 'Lista'), ('En Hub Despacho', 'En Hub Despacho'), ('Volando', 'Volando'), ('En Hub Llegada', 'En Hub Llegada'), ('Lista Recoger', 'Lista Recoger'), ('Entregada', 'Entregada'), ('Cancelada', 'Cancelada')], default='Creada', max_length=255)),
                ('hubEntrega', models.IntegerField(null=True)),
                ('hubRecepcion', models.IntegerField(null=True)),
                ('comprador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Usuario.Comprador')),
                ('items', models.ManyToManyField(to='Pedido.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='produc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pedido.Producto'),
        ),
    ]
