# Generated by Django 2.2 on 2021-09-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField(blank=True, default=None, null=True)),
                ('alto', models.FloatField(blank=True, default=None, null=True)),
                ('ancho', models.FloatField(blank=True, default=None, null=True)),
                ('largo', models.FloatField(blank=True, default=None, null=True)),
                ('peso', models.FloatField(blank=True, default=None, null=True)),
                ('cantidadDisponible', models.IntegerField()),
            ],
        ),
    ]
